### ISSUE TITLE
BREAKING CHANGE: New Scope property breaks DSC Resource

### ISSUE THREAD

**Issue by jpogran** [PowerShell/xPowerShellExecutionPolicy#14]
Commit cacd235633bd5e2d0537e209b345a88c3526279e added the `Scope` property to the xPowerShellExecutionPolicy DSC Resource, however according to the DMTF [specification](https://www.dmtf.org/sites/default/files/standards/documents/DSP0221_3.0.0.pdf) (page 37) `Scope` is a reserved keyword, and results in this DSC Resource being unusable. This change also prevents us from including this release in the Puppet [dsc module](https://forge.puppet.com/puppetlabs/dsc). I replicated this on PowerShell 5.1 on a fresh machine, with a `Install-Module -Name xPowerShellExecutionPolicy` using the PowerShellGallery feed, which pulls down version 2.0.0.0.

Attempting to use the DSC Resource results in a failure to find it:

```
PS C:\> Invoke-DscResource -Name xPowerShellExecutionPolicy -Property @{ ExecutionPolicy = 'RemoteSigned' } -Verbose -Method Test -ModuleName xPowerShellExecutionPolicy
Invoke-DscResource : Resource xPowerShellExecutionPolicy was not found as one of the builtin resources. Please add -ModuleName
parameter to include external resources.
At line:1 char:1
+ Invoke-DscResource -Name xPowerShellExecutionPolicy -Property @{ Exec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-DscResource], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.InvokeDscResourceMethod
   Command
```

This is because it fails parsing with the syntax error from usage of the word `scope`:

```
PS C:\> Get-DscResource
ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file C:\Program Files\Windows
PowerShell\Modules\xPowerShellExecutionPolicy\2.0.0.0\DSCResources\MSFT_xPowerShellExecutionPolicy\MSFT_xPowerShellExec
utionPolicy.Schema.mof.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143
char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromM
   odule

ImportCimAndScriptKeywordsFromModule : Syntax error:
 At line:6, char:276
 Buffer:
erPolicy"}] String Scope^;
};
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143
char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,ImportCimAndScriptKeywordsFromModule
```

The fix would be to choose a different name for the `Scope` property, something like `ScopeLevel` or `ExecutionPolicyScope`. I can put up a PR to fix that, but wanted to ask first what name to use.

**Comment by michaeltlombardi** [comment]
#9 is also impacted by this.

**Comment by TraGicCode** [comment]
I was able to verify this was broken as well.

**Comment by zjalexander** [comment]
@mgreenegit

**Comment by MattAllison** [comment]
I know I'm late to the party but I just hit this bug.  Recommend "PolicyScope" or "ExecutionPolicyScope" as the parameter name.  May be more intuitive than ScopeLevel.

**Comment by johlju** [comment]
@MattAllison Never to late to come with suggestions! @TraGicCode is working on this in PR #15. @TraGicCode what is you opinion about @MattAllison's proposal?

**Comment by TraGicCode** [comment]
I'm okay with the recommendation.  No problem on my end with changing this.  I'm in favor of long names so i shall pick ExecutionPolicyScope :).  Sound good @MattAllison ?

**Comment by johlju** [comment]
@TraGicCode we are three in favor of 'ExecutionPolicyScope' so I propose we go with that. 😃

**Comment by MattAllison** [comment]
I'm good with the verbose parameter name.  Thank you!

**Comment by TraGicCode** [comment]
I will work on this now.
