### ISSUE TITLE
Enable CodeCov Support

### ISSUE THREAD

**Issue by TraGicCode** [PowerShell/xPowerShellExecutionPolicy#18]
Hey @johlju ,

What is the process i need to follow in order to enable codecov for this?

**Comment by johlju** [comment]
1. PR #16 should be merged so tests are properly tested.
1. Add CodeCoverage and CodeCov parameters to the `Invoke-AppveyorTestScriptTask` helper function in appveyor.yml from the [appveyor.yml template](https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/appveyor.yml). *Note: It looks to me like you should be able to replace the entire appveyor.yml to the one in the template.*
1. Copy the [.codecov.yml](https://github.com/PowerShell/SqlServerDsc/blob/dev/.codecov.yml) from for example SqlServerDsc (added an issue to add it to the DscResource template folder).
1. Codecov should be enabled. I think this is already done on all repos. If the Codecov bot is adding a comment to the PR after the tests has run, then it works. If it does not, Codecov must be enable by PowerShell DSC team. 

I think that's it. 🤔
